FROM python:3.12-slim-bullseye
WORKDIR /myapp
COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "demo.asgi:application", "--host", "0.0.0.0", "--port", "8000"]
